g++: error: std=c++11: No such file or directory
./sample: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
./sample: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
./sample: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
./sample: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
/lustre/apps/anaconda/3/lib/python3.5/site-packages/matplotlib/axes/_axes.py:6016: RuntimeWarning: invalid value encountered in true_divide
  m = (m.astype(float) / db) / m.sum()
/lustre/apps/anaconda/3/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/lustre/apps/anaconda/3/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/lustre/apps/anaconda/3/lib/python3.5/site-packages/scipy/stats/_distn_infrastructure.py:872: RuntimeWarning: invalid value encountered in greater_equal
  return (self.a <= x) & (x <= self.b)
/lustre/apps/anaconda/3/lib/python3.5/site-packages/scipy/stats/_distn_infrastructure.py:872: RuntimeWarning: invalid value encountered in less_equal
  return (self.a <= x) & (x <= self.b)
